### ISSUE TITLE
Message confuzzleup

### ISSUE THREAD

**Issue by Funnytom118** [Funnytom118/Valkine#12]
http://prntscr.com/dkvwju

incorrect grammar/wording. I used /eco give

**Comment by Osto468** [comment]
ik that
I just c/p from /eco take, and forgot to fix it there - fixed it somewhere else tho...
#BlameTomTom2k16

**Comment by Funnytom118** [comment]
Please fix it lol, or when I'm editing all of the messages, I'll get confused!

**Comment by Osto468** [comment]
Fixeddddd
