### ISSUE TITLE
/balance

### ISSUE THREAD

**Issue by Funnytom118** [Funnytom118/Valkine#9]
On join, if the balance isn't set, set it to 0. http://prntscr.com/dkv1z9

**Comment by Osto468** [comment]
No
On join, if the balance isn't set, it will be set to the start bal
ffs

**Comment by Funnytom118** [comment]
Doesn't seem like it, as the start balance is over 0, so it should not say <none>, it should say 0.

**Comment by Osto468** [comment]
If it hasn't been set at all (if it was deleted manually, or you joined before it was put into effect), not if it is 0, you will recieve the starting balance. It is just a failsafe, and won't be used much if at all.

**Comment by Funnytom118** [comment]
Alright
